### ISSUE TITLE
Button-group is not working on ipad

### ISSUE THREAD

**Issue by mohan-subbu** [PredixDev/px-button-group-design#2]
Button-group is not working on ipad. It's not even showing the active button with blue color.
I have imported all the button-group related css files

**Comment by katemenkhaus** [comment]
It sounds like the styles are being not imported correctly. 
I have two simple examples below one for Polymer 1 and one for Polymer 2. Both examples work in  safari & chrome mobile. 

My .scss file
```
$inuit-enable-btn--primary : true;
@import 'px-buttons-design/_objects.buttons.scss';
@import "px-button-group-design/_objects.button-group.scss";
```

Polymer 2 example. The way styles are imported in Polymer 2 has changed. Note you can only have one `<style></style>` in a `<custom style></custom style>`.
```
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Predix UI</title>
  <script src="../../webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="../../polymer/polymer.html" />
  <link rel="import" href="../../px-theme/px-theme-styles.html">
  <link rel="import" href="../css/px-button-styles.html" />

  <custom-style>
    <style include="px-theme-styles" is="custom-style"></style>
  </custom-style>
  <custom-style>
    <style include="px-button-styles" is="custom-style"></style>
  </custom-style>
</head>
<body>
  
  <button class="btn">Label</button>

  <div class="btn-group">
    <input id="id1" name="btn-group"  type="radio">
    <label for="id1" class="btn">Label 1</label>
    <input id="id2" name="btn-group"  type="radio">
    <label for="id2" class="btn btn--primary">Label 2</label>
  </div>

</body>
</html>
```

Polymer 1 example 
```
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Predix UI</title>
  <script src="../../webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="../../polymer/polymer.html" />
  <link rel="import" href="../../px-theme/px-theme-styles.html">
  <link rel="import" href="../css/px-button-styles.html" />

  <style include="px-theme-styles" is="custom-style"></style>
  <style include="px-button-styles" is="custom-style"></style>
</head>
<body>
  
  <button class="btn">Label</button>

  <div class="btn-group">
    <input id="id1" name="btn-group"  type="radio">
    <label for="id1" class="btn">Label 1</label>
    <input id="id2" name="btn-group"  type="radio">
    <label for="id2" class="btn btn--primary">Label 2</label>
  </div>

</body>
</html>
```

**Comment by shrikumarhegde** [comment]
button group is not working in mobile as well. 
Even below example is not working as expected 
https://www.predix-ui.com/#/css/visual/buttons/px-button-group-design
1. select label 1 (button 1)
2. now try to click 2nd button. it wont work. it wont work in any touch devices. Only mouse click is working as of now

**Comment by randyaskin** [comment]
This is actually a known limitation of the `label` tag on WebKit mobile, they disable the behavior of automatically toggling a checkbox / radio button or focusing an input field, presumably to prevent interference with the tap-and-hold-to-select-text interaction. Aside from wrapping this component as a Polymer component, I'm not sure there's a pure HTML/CSS way to make this component work on mobile.
